name: TikTok Sandik Botu

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Kodları Çek
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Kütüphaneleri Yükle
        run: npm install

      - name: Botu Çalıştır
        run: node index.js
        
